// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtkxnwejhqctnpdmkdor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0a3hud2VqaHFjdG5wZG1rZG9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NDMxNjUsImV4cCI6MjA3MjExOTE2NX0.rVpSl1ooHInp8aPHD1QRx1y-UqALqJkkgPHmK-z5_NY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});